# Generated by Django 3.2.9 on 2021-11-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEA', '0004_analyticmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticmodel',
            name='analytic_plot',
            field=models.FileField(default='plot/<django.db.models.fields.CharField>.html', upload_to='plot'),
        ),
    ]
