# Generated by Django 3.2.9 on 2021-11-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEA', '0005_analyticmodel_analytic_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticmodel',
            name='analytic_plot',
            field=models.FileField(upload_to='plot'),
        ),
    ]
