# Generated by Django 3.2.9 on 2021-11-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEA', '0007_remove_analyticmodel_analytic_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticmodel',
            name='analytic_plot',
            field=models.FileField(default='temp.html', upload_to='plot'),
        ),
    ]
