# Generated by Django 3.2.9 on 2021-11-27 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IEA', '0008_analyticmodel_analytic_plot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticmodel',
            name='analytic_plot',
        ),
    ]
